package com.xantrix.webapp.entity;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.validation.constraints.Min;

//@DynamoDBTable(tableName = "DettListini")
@DynamoDBDocument
public class DettListini implements Serializable {
	private static final long serialVersionUID = 8777751177774522519L;

	@DynamoDBHashKey(attributeName = "DettListiniId")
	@DynamoDBAutoGeneratedKey
	private Integer id;

	@DynamoDBAttribute(attributeName = "CodArt")
	@Size(min = 5, max = 20, message = "{Size.DettListini.codArt.Validation}")
	@NotNull(message = "{NotNull.DettListini.codArt.Validation}")
	private String codArt;

	@DynamoDBAttribute(attributeName = "Prezzo")
	@Min(value = (long) 0.01, message = "{Min.DettListini.prezzo.Validation}")
	private Double prezzo;

	
	@JsonBackReference
	private Listini listino;

	public DettListini() {
	}

//	public DettListini(String CodArt, Double Prezzo, Listini Listino) {
//		this.codArt = CodArt;
//		this.prezzo = Prezzo;
//		this.listino = Listino;
//	}
//	
	@JsonCreator
	public DettListini(@JsonProperty("codArt") String CodArt, @JsonProperty("prezzo") Double Prezzo,
			@JsonProperty("listino") Listini Listino) {
	this.codArt = CodArt;
	this.prezzo = Prezzo;
	this.listino = Listino;
	}

	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getCodArt() {
		return codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}


	public Double getPrezzo() {
		return prezzo;
	}

	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}
	
	
	public Listini getListino() {
		return listino;
	}

	public void setListino(Listini listino) {
		this.listino = listino;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
