# ==============================================================
# = Articoli Web Service - Versione Base
# ==============================================================

server:
  port: 5001
  
spring:
  application:
    name: ProductsWebService

    
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: 07139
    platform: postgres
    url: jdbc:postgresql://localhost:5000/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl:  true
  main:
    allow-bean-definition-overriding: true
    
