# ==============================================================
# = Articoli Web Service - Versione Base
# ==============================================================

server:
  port: 5001
  
spring:
  application:
    name: ProductsWebService

    
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: ${RDS_PASSWORD:Alex1993!}
    platform: postgres
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5433}/${RDS_DB_NAME:Alphashop}
    username: ${RDS_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl:  true
  main:
    allow-bean-definition-overriding: true