<<<<<<< HEAD

=======
>>>>>>> alessio
# ==============================================================
# = Articoli Web Service - Versione Base
# ==============================================================

server:
<<<<<<< HEAD
  port: 5000
=======
  port: 5002
>>>>>>> alessio
  
spring:
  application:
    name: ProductsWebService
    
    
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: Alex1993!
    platform: postgres
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
<<<<<<< HEAD
=======
    generate-ddl:  true
>>>>>>> alessio
  main:
    allow-bean-definition-overriding: true


